SELECT 
    ROUTE,
    CONCAT(
        CASE 
            WHEN SUM(D_BETWEEN_DIST) = FLOOR(SUM(D_BETWEEN_DIST)) 
            THEN FLOOR(SUM(D_BETWEEN_DIST)) 
            ELSE ROUND(SUM(D_BETWEEN_DIST), 1) 
        END, 
        'km'
    ) AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM subway_distance
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;